### PR TITLE
Nuclear Rework part 3

### PR DESCRIPTION
**Pull request by Erik3003**
My last batch of changes to the nuclear fission system. This includes the rebalancing of some reactor coolants, having the chance to cause "explosions" in old designs using Molten Tin, Molten Sodium or Helium as coolant. The changelog has also been updated to document all changes in this and the past two pull requests for the user and offer a warning about this danger.

Other minor changes include slight rebalancing to depleted rod processing output, a slight increase to the neutron amounts needed for breeding and changes to Co-60 fuel rods. There is also a slightly important fix for a bug I discovered while testing caused by my changes to the durability system in part 1, where the coolant specific changes to the neutron maximum wouldn't be applied as well as moderation from specific coolant types.

Then there are two new config options added for a better reactor balance:

- EasyU235Extraction:  When false, will disable extracting U-235 from refined uranium ore. False by default.
- Enable1x1ReactorCore: When false, will disable the crafting recipe for the 1x1 reactor core. False by default.

Though I'm not entirely sure if these checks for the config should be where they are or if they should be moved to the main mod class. I would have liked to add disabling the 1x1 reactor recipe also disabling the block appearing in NEI, but I have absolutely no idea how that would be done.

These should hopefully be the last changes to the fission system. As always, these changes have been tested.

### CODE REVIEW

**Comment by GregoriusT** [comment]
Okay this might take a bit longer to review for me, so dont worry. ^^

**Comment by Erik3003** [comment]
I made a "last minute" change to tritium breeding, now requiring regular lithium instead of lithium-6, while making it a tiny bit harder to breed (slightly more neutrons required, significantly higher neutron loss, also more "consistent" choice of numbers more inline with the other breeding rods).

While lithium-6 is more realistic for breeding tritium, breeding it from regular litium-7 is in reality also possible, although requiring more energy. Since lithium-6 can just be used in the fusion reactor anyway at even greater energy output, I don't think using it for breeding tritium is really useful at all for the player.

**Comment by Erik3003** [comment]
Took me a while of doing nothing, but I added some guide books (9 useful, 1 flavor) for reactor mechanics that can be found in dungeon and stronghold library loot. That concludes my changes to this pull request, if there aren't any changes required after review.

**Comment by Erik3003** [comment]
Ok, this is really the last change. Just a small convenience feature for making building mixed coolant fission reactors less tedious: When the secondary facing of the reactor core gets set to the same direction as the primary, the secondary will be effectively disabled, not distributing any coolant. 

While a quadruple or nonuple pipe could have been used previously, I don't think that behavior was all that useful and the previous way of "turning off" the secondary facing by basically turning it into the direction of the coolant input came with the downside of the reactor pushing out coolant, which is not ideal and may cause some safety concerns for reactor operators.

**Pull request merged**
