### PR TITLE
Mold client-side calculations

### PR DESCRIPTION
**Pull request by ICaxapI**
Moved the calculation of the removed piece in the mold to the client side instead of the server side (on the server side this calculation is inaccurate due to positioning error)

P.s. Yes, I was ***very*** pissed off by another screwed up mold

### CODE REVIEW

**Comment by GregoriusT** [comment]
Hrrm, this might work, but I definitely need to do some Infrastructure work before I just put a random network handler in there, so I will keep this PR open for now. ^^

**Review by Trivoz — APPROVED** [review]

**Comment by Trivoz** [comment]
^ accident mb

**Comment by GregoriusT** [comment]
@ICaxapI uhm did you accidentially nuke this PR when you did the other one?

**Comment by ICaxapI** [comment]
Oops, indeed, I accidentally broke it.
Anyway, I noticed that it worked great in single player, but didn't work on a separately launched server and a remote client, and I have too little experience with mc network code to fix this. I can reopen the MR and revert these changes back, but they need refinement from experienced eyes.

**Pull request closed without merging**
